# build.yaml
targets:
  $default:
    builders:
      functional_widget:
        options:
          debugFillProperties: true
          widgetType: stateless
          equality: equal
        generate_for:
          include:
            - lib/**/*page.dart
      freezed:
        generate_for:
          include:
            - lib/**/*state.dart
            - lib/model/firestore/**/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/model/firestore/**/*.dart
        options:
          any_map: true
          explicit_to_json: true