name: flutter_bootstrap
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # state management
  state_notifier: ^0.7.0
  hooks_riverpod: ^0.13.0-nullsafety.3
  flutter_hooks: ^0.16.0
  subscription_holder: ^2.1.0
  # ui
  animations: ^2.0.0
  gap: ^2.0.0-nullsafety.1
  mono_kit: ^0.19.0+3
  adaptive_dialog: ^0.10.0+5
  font_awesome_flutter: ^9.0.0-nullsafety
  flutter_portal: ^0.4.0-nullsafety.0
  # Firebase
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  freezed_annotation: ^0.13.0-nullsafety.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.14.0-nullsafety.0
  pedantic_mono: ^1.11.0+2
  dart_code_metrics: ^2.4.0
flutter:
  uses-material-design: true
